title: Priyanka Nanayakkara
url: "https://priyakalot.github.io"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Publications"
   link: "publications"
 - name: "Public Writing"
   link: "writing"
 - name: "Teaching"
   link: "teaching"
